# github action that checks code with Rector
name: Rector

on: [push]

jobs:
    rector:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v3
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.ACCESS_TOKEN }}

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v2"

            -   run: vendor/bin/rector process --clear-cache

            -
                # commit only to core contributors who have repository access
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: '[rector] Rector fixes'
                    push_options: '--force'
