name: Split commits

on:
  push:
    branches: ['3.x']

concurrency:
  group: split

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - { namespace: AssetManager, repo: asset-manager }
          - { namespace: ColorManager, repo: color-manager }
          - { namespace: Contracts, repo: contracts }
          - { namespace: Core, repo: core }
          - { namespace: Laravel, repo: laravel }
          - { namespace: MenuManager, repo: menu-manager }
          - { namespace: Support, repo: support }
          - { namespace: UI, repo: ui }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          repo_url="https://${{ secrets.SUPER_ACCESS_TOKEN }}@github.com/moonshine-software/${{ matrix.package.repo }}.git"
          git subtree merge --prefix src/${{ matrix.package.namespace }} "$repo_url" ${{ github.ref_name }}
          git subtree push --prefix src/${{ matrix.package.namespace }} "$repo_url" ${{ github.ref_name }}
